### ISSUE TITLE
About skip connections

### ISSUE THREAD

**Issue by naoki7090624** [kobeshegu/ECCV2022_WaveGAN#1]
Hi,
Thank you for sharing great works!!

I have questions about skip connections of generator. According to Fig.2 in your paper, the wavepool from the first layer of the encoder is added with the output from the first conv layer of the decoder. However, in your code, the wavepool from the fourth layer of the encoder is added with the output from first layer of the docoder.
Also, the addition before the `conv4` and `conv5` of the decoder is not done in your code.
```
x6 = self.Conv3(x5+x_deconv4)
x7 = self.Upsample(x6)
x8 = self.Conv4(x7)
x9 = self.Conv5(x8)
```
Why is the code different from the figure in the paper?

Thank you in advance.

**Comment by kobeshegu** [comment]
Hi, there. 
Thanks a lot for your comments.
We notice that the skip connection of Fig.2 in our paper is incorrect since we perform skip connections to integrate the inversed high-frequency components to the features which have the same dimension with the inversed components as down in the code, as well as consistent with the description in Sec. 3.3 in our paper. 
We are sorry for the misunderstanding and will correct printing errors.
(2) we perform 4 skip connections for our experiments, fell free to uncomment to see the results.
```

        # LH4, HL4, HH4 = skips['pool1']
        # original4 = skips['conv1_1']
        # c, h, w = LH4.size()[-3:]
        # LH4, HL4, HH4 = LH4.view(8, 3, c, h, w).mean(dim=1), HL4.view(8, 3, c, h, w).mean(dim=1), HH4.view(8, 3, c, h,w).mean(dim=1)
        # x_deconv3 = self.recon_block3(x6, LH4, HL4, HH4, original3)
```
Fell free to contact me at kobeshegu@gmail.com if you have any further questions.

**Comment by kobeshegu** [comment]
> Hi, Thank you for sharing great works!!
> 
> I have questions about skip connections of generator. According to Fig.2 in your paper, the wavepool from the first layer of the encoder is added with the output from the first conv layer of the decoder. However, in your code, the wavepool from the fourth layer of the encoder is added with the output from first layer of the docoder. Also, the addition before the `conv4` and `conv5` of the decoder is not done in your code.
> 
> ```
> x6 = self.Conv3(x5+x_deconv4)
> x7 = self.Upsample(x6)
> x8 = self.Conv4(x7)
> x9 = self.Conv5(x8)
> ```
> 
> Why is the code different from the figure in the paper?
> 
> Thank you in advance.

We have updated our paper and uploaded to arxiv, thanks again for your correction.
